// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppIcon: typeof import('./components/common/AppIcon.vue')['default']
    LazyImg: typeof import('./components/common/LazyImg.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheHeader: typeof import('./components/App/TheHeader.vue')['default']
    TheTabbar: typeof import('./components/App/TheTabbar.vue')['default']
    UPButton: typeof import('./components/App/UPButton.vue')['default']
  }
}

export { }
